<Project>

  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
  </PropertyGroup>

  <ItemGroup>

    <PackageVersion Include="Asp.Versioning.Http" Version="10.2.2" />

    <PackageVersion Include="Microsoft.AspNetCore.OpenApi" Version="10.0.0" />

    <PackageVersion Include="Microsoft.OpenApi" Version="2.0.0" />

    <PackageVersion Include="OpenTelemetry" Version="1.17.0" />

    <PackageVersion Include="OpenTelemetry.Extensions.Hosting" Version="1.17.0" />

    <PackageVersion Include="OpenTelemetry.Exporter.Console" Version="1.17.0" />

    <PackageVersion Include="OpenTelemetry.Instrumentation.AspNetCore" Version="1.17.0" />

    <PackageVersion Include="Microsoft.Extensions.Diagnostics.HealthChecks" Version="10.0.0-preview.7" />

    <PackageVersion Include="Microsoft.CodeAnalysis.NetAnalyzers" Version="9.0.0" />

    <PackageVersion Include="Roslynator.Analyzers" Version="4.12.0" />

    <PackageVersion Include="Serilog.AspNetCore" Version="9.0.0" />

    <PackageVersion Include="Serilog.Sinks.Console" Version="6.0.0" />

    <PackageVersion Include="Scalar.AspNetCore" Version="2.1.0" />

    <PackageVersion Include="Yarp.ReverseProxy" Version="2.3.0" />

    <PackageVersion Include="StyleCop.Analyzers" Version="1.2.0-beta.556" />

    <PackageVersion Include="xunit" Version="2.9.3" />
    <PackageVersion Include="xunit.runner.visualstudio" Version="2.8.2" />
    <PackageVersion Include="Microsoft.NET.Test.Sdk" Version="17.14.1" />

  </ItemGroup>

</Project>